name: docdoc
description: "DocDoc — doctor appointment booking app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  get_it: ^9.2.1
  dio: ^5.9.2
  pretty_dio_logger: ^1.4.0
  flutter_native_splash: ^2.4.7
  flutter_svg: ^2.2.4
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
    - assets/icons/

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#FFFFFF"
  image: assets/icons/docdoc_app_icon.png
  image_dark: assets/icons/docdoc_app_icon.png
  android: true
  ios: true
  web: false
  android_12:
    color: "#FFFFFF"
    color_dark: "#FFFFFF"
    image: assets/icons/docdoc_app_icon.png
    image_dark: assets/icons/docdoc_app_icon.png
    icon_background_color: "#FFFFFF"
    icon_background_color_dark: "#FFFFFF"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/docdoc_app_icon.png"
  remove_alpha_ios: true
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/docdoc_app_icon.png"
